#!/usr/bin/env python

from gradelib import *
import re

r = Runner(save("jos.out"),
           stop_breakpoint("readline"))

@test(0, "running JOS")
def test_jos():
    r.run_qemu()

@test(15, parent=test_jos)
def test_infopg_total_PDEs():
    match = re.findall(r"PDE", r.qemu.output)
    assert_equal(len(match), 67)

@test(15, parent=test_jos)
def test_infopg_total_PTEs():
    match = re.findall(r"PTE", r.qemu.output)
    assert_equal(len(match), 87)

@test(40, parent=test_jos)
def test_infopg_page_entry_without_any_flags():
    match = re.findall(r"---------", r.qemu.output)
    assert_equal(len(match), 2, "flags should have ---------")

@test(30, parent=test_jos)
def test_infopg_page_entry_with_user_and_present_flag():
    match = re.findall(r"------U-P", r.qemu.output)
    assert_equal(len(match), 2, "flags should have ------U-P")

run_tests()
